@baseURL = http://localhost:8000

###

# @name post_resp
POST {{baseURL}}/entries HTTP/1.1
content-type: application/json

{
  "work": "Studied GCP and built my first endpoints on cloud",
  "struggle": "Understanding async/await syntax and when to use it",
  "intention": "Practice PostgreSQL queries and database design"
}

###

# Added .entry. to the path
@id = {{post_resp.response.body.entry.id}}


### 

GET {{baseURL}}/entries/{{id}}

###

# @name get_resp

GET {{baseURL}}/entries

@ids = {{get_resp.response.body.entries[0].id}}

###

GET {{baseURL}}/entries/fakefake12345

###

DELETE {{baseURL}}/entries/{{ids}}

###

PATCH {{baseURL}}/entries/{{ids}}
content-type: application/json

{
  "additionalProp1": {}
}

###

POST {{baseURL}}/entries/{{ids}}/analyze HTTP/1.1
content-type: application/json